### ISSUE TITLE
Click in the "Forum Channel" breadcrumb goes to wrong page

### ISSUE THREAD

**Issue by npracht** [mautic/website#20]
# Description
On http://staging.mautic.org/forum/topic/mautic-installation-different-websites, Click in the "Forum Channel" breadcrumb goes to wrong page.

![capture d ecran 2019-02-13 a 09 51 06](https://user-images.githubusercontent.com/14075239/52698940-e79c4200-2f74-11e9-9059-37c3c264ea02.png)

**Comment by kuzmany** [comment]
We need rework urls and logic to forum/channel-name/topic-name 
Then we will able do that like in Mauticamps and Translations.
Working on it

**Comment by RCheesley** [comment]
This might be a simple fix, let's chat about it

**Comment by kuzmany** [comment]
Do you mean there is another way how to do it? 
I tried few ways, but without success :(

**Comment by RCheesley** [comment]
OK so I think I know what the problem is here, at least I have a hunch.  Ultimately this breadcrumbs plugin is for pages, and I don't think it's set up to be used on forums.

It *could* be related to the fact that with OctoberCMS, when you use a parameter in the URL slug, you can only use it at the end of the URL. You can't have parameters in the middle of a URL. See reference here: https://octobercms.com/docs/cms/pages#url-syntax

I'm not sure if that is the case, what I think might be happening is that when we are using the forum breadcrumb, the category page we are selecting as the 'parent' of the forum posts has a parameter in its URL:

/forum/channel/:channelslug

So the URL becomes, for example, forum/channel/general-discussion

When we go into a topic, we have the breadcrumb set to use this as the parent.  So I think this is where the problem lies - it doesn't know the category when it's on the individual post, so it is falling back to 'default'.

I have posted on the RainLab Forum plugin GH here: https://github.com/rainlab/forum-plugin/issues/132

**Comment by kuzmany** [comment]
I can handle it. 
I am going to fixed it

**Comment by kuzmany** [comment]
New fixed 

http://staging.mautic.org/forum/topic/benefits-and-advantages-of-voice-broadcasting

**Comment by RCheesley** [comment]
Perfect! Tested in several categories and works great!
