### ISSUE TITLE
content broken on logo and graphic page

### ISSUE THREAD

**Issue by npracht** [mautic/website#23]
# Description
On http://staging.mautic.org/about/logos-and-graphics, the content is broken.
This is because the path is a direct copy/paste from existing page. It should be /storage/app/media - and none of the images are uploaded there. Tested with the first image, and it works. May need to decide if you're going to offload images to S3 though, and set up that first?
Layout is broken on current site, so it just needs twig-ifying I think.

**Comment by RCheesley** [comment]
For now, I will update the file paths in the content file - will add the S3 question as a related card.

**Comment by RCheesley** [comment]
This is now resolved, I have re-used existing card-based styling from other pages to create the visual styling/layout.

http://staging.mautic.org/about/logos-and-graphics

Related issues above will need addressing before this is completely 'ready' as there are some broken links due to missing files, and brand-teal is not defined in the CSS so it does not appear in the card highlight at the bottom of the page.
